server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC

stats:
  url: ${STATS_SERVER_URL:http://stats-server:9090}

app:
  name: ewm-main-service

management:
  endpoints:
    web:
      exposure:
        include: health,info