version: '3.8'

services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "6541:5432"
    volumes:
      - stats-data:/var/lib/postgresql/data

  stats-server:
    build: ./stats-server
    container_name: stats-server
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "9090:9090"

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "6542:5432"
    volumes:
      - ewm-data:/var/lib/postgresql/data

  ewm-service:
    build: ./main-service
    container_name: ewm-service
    depends_on:
      - ewm-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

volumes:
  stats-data:
  ewm-data: